"""added timestamps to table

Revision ID: 227af59b590e
Revises: eae5356f072b
Create Date: 2020-11-24 15:25:42.984812

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '227af59b590e'
down_revision = 'eae5356f072b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('country', sa.Column('created_at', sa.TIMESTAMP(), nullable=False))
    op.add_column('country', sa.Column('updated_at', sa.TIMESTAMP(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('country', 'updated_at')
    op.drop_column('country', 'created_at')
    # ### end Alembic commands ###
