"""change name table

Revision ID: 30d601db04d3
Revises: 4b69c3398f55
Create Date: 2020-11-24 14:03:42.932929

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '30d601db04d3'
down_revision = '4b69c3398f55'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('country',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=2), nullable=False),
    sa.Column('name', sa.String(length=127), nullable=True),
    sa.Column('phone_code', sa.String(length=16), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('country_names')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('country_names',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('code', sa.VARCHAR(length=2), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(length=127), autoincrement=False, nullable=True),
    sa.Column('phone_code', sa.VARCHAR(length=16), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='country_names_pkey')
    )
    op.drop_table('country')
    # ### end Alembic commands ###
