"""added unique for code

Revision ID: 7141f99325e0
Revises: 227af59b590e
Create Date: 2020-11-24 21:00:56.193476

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7141f99325e0'
down_revision = '227af59b590e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'country', ['code'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'country', type_='unique')
    # ### end Alembic commands ###
